### PR TITLE
update warning presence in Microsoft.Build.Locator.targets

### PR DESCRIPTION
**Pull request by YuliiaKovalova**
Fixes: https://github.com/microsoft/MSBuildLocator/issues/89

### CODE REVIEW

**Review by rainersigwald — CHANGES_REQUESTED** [review]
Does this work? It looks like it should hit https://github.com/dotnet/msbuild/issues/1155

**Comment by ladipro** [comment]
> Does this work? It looks like it should hit [dotnet/msbuild#1155](https://github.com/dotnet/msbuild/issues/1155)

+1, this does not build.

@YuliiaKovalova, in addition to fixing it could you please also add

```xml
  <Import Project="..\..\src\MSBuildLocator\build\Microsoft.Build.Locator.targets"/>
```

to BuilderApp.csproj so this file is covered by CI?

**Comment by YuliiaKovalova** [comment]
> > Does this work? It looks like it should hit [dotnet/msbuild#1155](https://github.com/dotnet/msbuild/issues/1155)
> 
> +1, this does not build.
> 
> @YuliiaKovalova, in addition to fixing it could you please also add
> 
> ```
>   <Import Project="..\..\src\MSBuildLocator\build\Microsoft.Build.Locator.targets"/>
> ```
> 
> to BuilderApp.csproj so this file is covered by CI?

I was inspired by https://stackoverflow.com/questions/3289538/is-there-any-msbuild-task-to-check-if-a-string-contains-another-string-similar 

:) I will doublecheck

**Comment by ladipro** [comment]
> I was inspired by https://stackoverflow.com/questions/3289538/is-there-any-msbuild-task-to-check-if-a-string-contains-another-string-similar

Yes, it works for properties but sadly not for metadata.

> Should I check it with a regular expression?

I don't think so. Please check [this comment](https://github.com/dotnet/msbuild/issues/1155#issuecomment-533555365).

**Comment by YuliiaKovalova** [comment]
> > I was inspired by https://stackoverflow.com/questions/3289538/is-there-any-msbuild-task-to-check-if-a-string-contains-another-string-similar
> 
> Yes, it works for properties but sadly not for metadata.
> 
> > Should I check it with a regular expression?
> 
> I don't think so. Please check [this comment](https://github.com/dotnet/msbuild/issues/1155#issuecomment-533555365).

It works, thank you !

**Review by ladipro — APPROVED** [review]
LGTM. Please wait for @rainersigwald's approval before merging.

**Comment by YuliiaKovalova** [comment]
@rainersigwald , please review the changes.

**Review by rainersigwald — APPROVED** [review]
Sorry, I seem to have totally missed this from a couple of weeks ago. LGTM!

**Pull request merged**
